name: ppa_flutter
description: "Aplikasi Pelaporan PPA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Package wajib untuk kode kamu:
  http: ^1.6.0
  google_fonts: ^8.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  flutter_map: ^8.3.2
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Opsional: jika nanti ada aset gambar lokal
  # assets:
  #   - assets/images/